# debian 12 - bookworm
FROM debian:bookworm-20230814

RUN \
    apt-get clean && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y -q --no-install-recommends \
	bash-completion \
	build-essential \
	chrpath \
	cpio \
	diffstat \
	file \
	g++-multilib \
	gawk \
	gcc-multilib \
	git-core \
	less \
	libncurses-dev \
	locales \
	lz4 \
	procps \
	openssh-client \
	pipx \
	python3 \
	python3-distutils \
	python3-pip \
	python-is-python3 \
	rsync \
	socat \
	sudo \
	sysstat \
	texinfo \
	tmux \
	unzip \
	vim \
	wget \
	xz-utils \
	zstd \
    && rm -rf /var/lib/apt/lists/* && \
    echo 'en_US.UTF-8 UTF-8' > /etc/locale.gen && \
    locale-gen

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN \
    wget -O /usr/local/bin/phyLinux https://download.phytec.de/Software/Linux/Yocto/Tools/phyLinux && \
    chmod a+x /usr/local/bin/phyLinux && \
    wget -O /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo && \
    chmod a+x /usr/local/bin/repo

RUN PIPX_HOME=/opt/pipx PIPX_BIN_DIR=/usr/local/bin PIPX_MAN_DIR=/usr/local/share/man pipx install kas==5.0
