FROM ubuntu:22.04

RUN \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y -q --no-install-recommends \
	-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
	locales \
	wget \
	git \
	cmake \
	ninja-build \
	gperf \
	ccache \
	dfu-util \
	device-tree-compiler \
	wget \
	python3-dev \
	python3-pip \
	python3-setuptools \
	python3-tk \
	python3-wheel \
	python3-venv \
	xz-utils \
	file \
	make \
	gcc \
	gcc-multilib \
	g++-multilib \
	libsdl2-dev \
	libmagic1 \
    && rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.6/zephyr-sdk-0.16.6_linux-x86_64.tar.xz && wget -O - https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.16.6/sha256.sum | shasum --check --ignore-missing
RUN tar xvf zephyr-sdk-0.16.6_linux-x86_64.tar.xz
RUN rm zephyr-sdk-0.16.6_linux-x86_64.tar.xz


RUN cd zephyr-sdk-0.16.6 && ./setup.sh -c
