FROM ubuntu:22.04

RUN \
    apt-get update && \
    DEBIAN_FRONTEND="noninteractive" apt-get install -y -q --no-install-recommends \
	-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
	bc \
	bison \
	bsdmainutils \
	build-essential \
	chrpath \
	cpio \
	diffstat \
	file \
	flex \
	g++-multilib \
	gawk \
	gcc-multilib \
	git-core \
	gnupg \
	iputils-ping \
	kas \
	less \
	libegl1-mesa \
	libgmp-dev \
	libmpc-dev \
	libncurses-dev \
	libsdl1.2-dev \
	libssl-dev \
	locales \
	lz4 \
	openssh-client \
	pylint \
	python2 \
	python3 \
	python3-distutils \
	python3-git \
	python3-jinja2 \
	python3-pexpect \
	python3-pip \
	python-is-python3 \
	socat \
	sudo \
	texinfo \
	tmux \
	unzip \
	vim \
	wget \
	xterm \
	zstd \
    && rm -rf /var/lib/apt/lists/* && \
    locale-gen en_US.UTF-8

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'

RUN \
    apt-get update && \
    apt-get install -y -q --no-install-recommends \
	-o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
	ca-certificates \
    && rm -rf /var/lib/apt/lists/* && \
    wget -O /usr/local/bin/phyLinux https://download.phytec.de/Software/Linux/Yocto/Tools/phyLinux && \
    chmod a+x /usr/local/bin/phyLinux && \
    wget -O /usr/local/bin/repo https://storage.googleapis.com/git-repo-downloads/repo && \
    chmod a+x /usr/local/bin/repo
